=== chartpath/ramses-elasticsearch/gii_api/gii_schema.json
{
    "type": "object",
    "title": "GII Country schema",
    "$schema": "http://json-schema.org/draft-04/schema",
    "required": ["country"],
    "properties": {
        "labour_force_participation_rate_aged_15_and_above_male_2012": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
                }
        },
        "hdi_rank": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "integer"
            }
        },
        "gender_inequality_index_value_2013": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "gender_inequality_index_rank_2013": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "country": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "string",
                "primary_key": true
            }
        },
        "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "labour_force_participation_rate_aged_15_and_above_female_2012": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "_2013_share_of_seats_in_parliament_held_by_women": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012": {
            "type": ["string","null"],
            "_db_settings": {
                "type": "float"
            }
        },
        "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births": {
            "type": ["integer","null"],
            "_db_settings": {
                "type": "integer"
            }
        }
    }
}

=== chartpath/ramses-elasticsearch/gii_api/gii_data.json
[ {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "69.5",
  "hdi_rank" : "1",
  "gender_inequality_index_value_2013" : "0.068",
  "gender_inequality_index_rank_2013" : "9",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "97.4",
  "country" : "Norway",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "7.8",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "61.5",
  "_2013_share_of_seats_in_parliament_held_by_women" : "39.6",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "96.7",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "7"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "71.9",
  "hdi_rank" : "2",
  "gender_inequality_index_value_2013" : "0.113",
  "gender_inequality_index_rank_2013" : "19",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "94.3",
  "country" : "Australia",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "12.1",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "58.8",
  "_2013_share_of_seats_in_parliament_held_by_women" : "29.2",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "94.6",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "7"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "75.3",
  "hdi_rank" : "3",
  "gender_inequality_index_value_2013" : "0.030",
  "gender_inequality_index_rank_2013" : "2",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "95.0",
  "country" : "Switzerland",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "1.9",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "61.2",
  "_2013_share_of_seats_in_parliament_held_by_women" : "27.2",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "96.6",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "8"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "87.3",
  "hdi_rank" : "4",
  "gender_inequality_index_value_2013" : "0.057",
  "gender_inequality_index_rank_2013" : "7",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "87.7",
  "country" : "Netherlands",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "6.2",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "79.9",
  "_2013_share_of_seats_in_parliament_held_by_women" : "37.8",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "90.5",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "6"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "69.3",
  "hdi_rank" : "5",
  "gender_inequality_index_value_2013" : "0.262",
  "gender_inequality_index_rank_2013" : "47",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "95.1",
  "country" : "United States",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "31.0",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "56.8",
  "_2013_share_of_seats_in_parliament_held_by_women" : "18.2",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "94.8",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "21"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "66.4",
  "hdi_rank" : "6",
  "gender_inequality_index_value_2013" : "0.046",
  "gender_inequality_index_rank_2013" : "3",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "96.3",
  "country" : "Germany",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "3.8",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "53.5",
  "_2013_share_of_seats_in_parliament_held_by_women" : "32.4",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "97.0",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "7"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "73.9",
  "hdi_rank" : "7",
  "gender_inequality_index_value_2013" : "0.185",
  "gender_inequality_index_rank_2013" : "34",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "95.0",
  "country" : "New Zealand",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "25.3",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "62.1",
  "_2013_share_of_seats_in_parliament_held_by_women" : "32.2",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "95.3",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "15"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "71.2",
  "hdi_rank" : "8",
  "gender_inequality_index_value_2013" : "0.136",
  "gender_inequality_index_rank_2013" : "23",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "100.0",
  "country" : "Canada",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "14.5",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "61.6",
  "_2013_share_of_seats_in_parliament_held_by_women" : "28.0",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "100.0",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "12"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "77.5",
  "hdi_rank" : "9",
  "gender_inequality_index_value_2013" : "0.090",
  "gender_inequality_index_rank_2013" : "15",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "74.1",
  "country" : "Singapore",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "6.0",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "59.0",
  "_2013_share_of_seats_in_parliament_held_by_women" : "24.2",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "81.0",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "3"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "67.5",
  "hdi_rank" : "10",
  "gender_inequality_index_value_2013" : "0.056",
  "gender_inequality_index_rank_2013" : "5",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "95.5",
  "country" : "Denmark",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "5.1",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "59.1",
  "_2013_share_of_seats_in_parliament_held_by_women" : "39.1",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "96.6",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "12"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "67.9",
  "hdi_rank" : "11",
  "gender_inequality_index_value_2013" : "0.115",
  "gender_inequality_index_rank_2013" : "20",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "80.5",
  "country" : "Ireland",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "8.2",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "52.7",
  "_2013_share_of_seats_in_parliament_held_by_women" : "19.5",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "78.6",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "6"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "68.1",
  "hdi_rank" : "12",
  "gender_inequality_index_value_2013" : "0.054",
  "gender_inequality_index_rank_2013" : "4",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "86.5",
  "country" : "Sweden",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "6.5",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "60.2",
  "_2013_share_of_seats_in_parliament_held_by_women" : "44.7",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "87.3",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "4"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "77.3",
  "hdi_rank" : "13",
  "gender_inequality_index_value_2013" : "0.088",
  "gender_inequality_index_rank_2013" : "14",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "91.0",
  "country" : "Iceland",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "11.5",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "70.6",
  "_2013_share_of_seats_in_parliament_held_by_women" : "39.7",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "91.6",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "5"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "68.8",
  "hdi_rank" : "14",
  "gender_inequality_index_value_2013" : "0.193",
  "gender_inequality_index_rank_2013" : "35",
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "99.8",
  "country" : "United Kingdom",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "25.8",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "55.7",
  "_2013_share_of_seats_in_parliament_held_by_women" : "22.6",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "99.9",
  "_2010_maternal_mortality_ratio_deaths_per_100_000_live_births" : "12"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "68.0",
  "hdi_rank" : "15",
  "gender_inequality_index_value_2013" : null,
  "gender_inequality_index_rank_2013" : null,
  "population_with_some_secondary_ed_aged_25_and_up_fem_2005_2012" : "72.2",
  "country" : "Hong Kong, China (SAR)",
  "_2010_2015_adolescent_birth_rate_births_per_1_000_women_aged_15_19" : "3.3",
  "labour_force_participation_rate_aged_15_and_above_female_2012" : "51.6",
  "population_with_some_secondary_ed_aged_25_and_up_male_2005_2012" : "79.2"
}
, {
  "labour_force_participation_rate_aged_15_and_above_male_2012" : "72.0",
